### ISSUE TITLE
Scrolldown Click Event

### ISSUE THREAD

**Issue by SorrisoPraFoto** [jonmbake/react-terminal-ui#14]
Hi,

Continuing my suggestion from the issue #12 , the scrolldown event on is triggered onClick when the pages has a height more than 100vh.

I made a video showing this using the demo terminal, I putted a **div element test** before the terminal and increased the height of the body, making a bigger site, and you will see the scrolldown animation to the final line in the terminal, thats what I suggest to remove, soo the dev's can implement it manually and optionally.

https://user-images.githubusercontent.com/14830148/121018958-5b317100-c775-11eb-963a-a52aafedcc6b.mp4

**Comment by jonmbake** [comment]
@SorrisoPraFoto A fix was pushed for this issue. Can you try out v0.1.13 and confirm that it is fixed?

**Comment by SorrisoPraFoto** [comment]
It's Working!

Thank u soo much for that, for real.
