### ISSUE TITLE
'Terminal hidden input' div is visible

### ISSUE THREAD

**Issue by TonyAttalla** [jonmbake/react-terminal-ui#15]
**Describe the bug**
the 'Terminal hidden input' div is visible in the terminal (as of the latest version)

**To Reproduce**
1. Create a new instance of the terminal
This issue can also be viewed on the demo site. 
**Expected behavior**
This div shouldn't be visible

**Screenshots**
![image](https://user-images.githubusercontent.com/39226687/122687700-c5bac600-d1e5-11eb-9453-af42163beb19.png)

**Additional context**
This issue can be resolved by rolling back to version 0.1.10

**Comment by jonmbake** [comment]
@TonyAttalla This is fixed in v0.1.14. Thanks for taking the time to open up this issue.

**Comment by TonyAttalla** [comment]
> @TonyAttalla This is fixed in v0.1.14. Thanks for taking the time to open up this issue.

Awesome, thank you. Will update.
