### ISSUE TITLE
Improve react-terminal-ui - Take the survey!

### ISSUE THREAD

**Issue by jonmbake** [jonmbake/react-terminal-ui#19]
Help improve _react-terminal-ui_ by answering the following questions:

1. **What do you like most about _react-terminal-ui_? What features do you find most useful?**
2. **What features do you feel are missing from _react-terminal-ui_? How could this project be improved?**
3. **Why are you using _react-terminal-ui_? i.e. What is the use case?**

**Comment by camheras** [comment]
Update the dependency from react@"^16.13.1" to react@"^17.0.0". Getting "Could not resolve dependency"...

**Comment by jonmbake** [comment]
> Update the dependency from react@"^16.13.1" to react@"^17.0.0". Getting "Could not resolve dependency"...

The react peer dependency has been updated to `>16.13.0`. You should no longer get that error, @camheras, as of v0.2.1. Thanks for submitting the issue.
