### ISSUE TITLE
Allow overriding default height

### ISSUE THREAD

**Issue by FaresKi** [jonmbake/react-terminal-ui#24]
**Is your feature request related to a problem? Please describe.**
I'm trying to make my terminal full screen, unlike the way it currently is:
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/46092308/177006345-43ccf64a-6955-45b2-9eb0-e503cbc36d6d.png">

**Describe the solution you'd like**
From a quick glance in your repo, it seems that the style.css limits the width and the height for the terminal itself, I'd like to have the option to provide a css or at least properties with the Terminal component.
**Describe alternatives you've considered**
Tried providing my own css, it got overridden by the default one.

**Comment by jonmbake** [comment]
[Terminal width is set to 100% by default](https://github.com/jonmbake/react-terminal-ui/blob/master/src/style.css#L9). Is the issue only with the height?

**Comment by antanasramana** [comment]
It is impossible to override height. Is it possible for you to change the default height to 100% so the terminal height would be controlled by the element that contains it?

**Comment by jonmbake** [comment]
@antanasramana There is not a great way to override the height right now. It would require a small update to make it easier.

**Comment by drageelr** [comment]
If anyone's still looking for a solution, I solved the problem by using a `useEffect` hook as follows:

**Comment by drageelr** [comment]
If anyone's still looking for a work around, I solved the problem by using a `useEffect` hook as follows:
```js
useEffect(() => {
  if (wrapperDiv === undefined) {
    wrapperDiv = document.getElementsByClassName('react-terminal-wrapper')[0];
    wrapperDiv.setAttribute('style', `height: ${HEIGHT};`);
  }
});
```

However, I think a better solution would be to allow a `height` prop to be passed to the `Terminal` component that sets the wrapper-div's `height` @jonmbake.

**Comment by drageelr** [comment]
@jonmbake the `height` prop should be applied to the outermost div (the one who's class is `react-terminal-wrapper`), not the one inside it I think.

**Comment by jonmbake** [comment]
@drageelr I basically moved height from the [`.react-terminal` style.css rule](https://github.com/jonmbake/react-terminal-ui/commit/a867dc72ceb55595962b2a4ea3c6857787032a48#diff-1104bdfdc4d3b01a85d7af489598121125db6bc016db2a48a083ef654c97b0f5L22) to a prop.

It seems to work from my testing:
```
 <Terminal name='React Terminal UI' colorMode={ colorMode }  onInput={ onInput } height="1000px">
  {lineData}
</Terminal>
```

Renders a `1000px` height terminal:

<img width="1146" alt="Screenshot 2023-02-04 at 5 37 46 AM" src="https://user-images.githubusercontent.com/865534/216765240-37d867c7-6814-40c2-833d-802d8d1a1f53.png">

Can you upgrade to v1.0.1 and try it out?

**Comment by drageelr** [comment]
Yes, tested it out. It's working. Great job!
