### ISSUE TITLE
Click callback for window buttons

### ISSUE THREAD

**Issue by Alvinn8** [jonmbake/react-terminal-ui#25]
**Is your feature request related to a problem? Please describe.**
There is no way to add click listeners to the macOS-style buttons on the terminal window. 

**Describe the solution you'd like**
A way to pass a callback for when the buttons are pressed to the Terminal component.

**Describe alternatives you've considered**
Fork the project and add the listeners.

**Additional context**
An example use case is closing, minimizing and maximizing the terminal window when the buttons are passed.

**Comment by nfacha** [comment]
+1 For this

**Comment by jonmbake** [comment]
This should be relatively easy to implement. The buttons are currently rendered as a [CSS pseudo element](https://github.com/jonmbake/react-terminal-ui/blob/v0.2.1/src/style.css#L33). We'd have to change them to something like a HTML button element instead and add `onClick`s.
