### ISSUE TITLE
is there a way to change font settings?

### ISSUE THREAD

**Issue by MeyerBuaharon** [jonmbake/react-terminal-ui#27]
is there a way to edit the font size, color, height etc..? if there is, sorry I haven't found it

**Comment by jonmbake** [comment]
You should be able to override any of the CSS rules defined in https://github.com/jonmbake/react-terminal-ui/blob/master/src/style.css with your own styling similar to what we are doing in the demo here: https://github.com/jonmbake/react-terminal-ui/blob/master/demo/index.tsx#L5. For example to change, the font family for the demo, we'd add:
```
div.react-terminal-wrapper {
    font-family: 'some-font-family'
}
```
to the demo's `style.css`. We may want to think of ways to make this easier in the future.

**Comment by MeyerBuaharon** [comment]
Ohhh... thank you!!
Loved the new changes you did with the TerminalInput/TerminalOutput keep the great work!
