### ISSUE TITLE
When updating two terminals at the same page, only one terminal scroll to bottom

### ISSUE THREAD

**Issue by MeyerBuaharon** [jonmbake/react-terminal-ui#28]
**Describe the bug**
When there are multiple terminals, and they are being updated with the same state, only one terminal will scroll to the bottom

**To Reproduce**
Make more then one terminal, and have them to use <TerminalOutput> from the same array of lines, that updates on input or something like that

**Expected behavior**
Both of the terminal scroll to the bottom and show new lines written

**Screenshots**
![image](https://user-images.githubusercontent.com/40149670/196614570-ec222b96-c199-4f4d-896b-7e47330f0543.png)

**Additional context**

**Comment by jonmbake** [comment]
Thanks for opening this issue, @MeyerBuaharon . Feel free to open a PR if you have a fix!
