### ISSUE TITLE
wrong cursor position

### ISSUE THREAD

**Issue by MohammadSabriExalt** [jonmbake/react-terminal-ui#34]
An ambiguous behavior happens when I write some characters in the terminal and click on the left arrow, the cursor position indicates that I am at the last character, but actually it's behind it.

The issue will be clear when i tried to clean what was written and press the backspace, it will leave some characters unremoved 

**To Reproduce**
1. write some characters to the terminal :ex 'ABCD'
2. press the left arrow 3 times 
3. wrie another characters ex: 'EFG'
4. the terminal shows (AEFGBCD)
5. press down  and hold the backspace to remove all
6. The terminal will shows "BCD"  and the cursor blinking after the "D"

**Expected behavior**
clear indication for the cursor position

**Screenshots**
![image](https://user-images.githubusercontent.com/101578040/225028013-015b0a83-1dfe-4d40-ac3b-684321d102ca.png)
![image](https://user-images.githubusercontent.com/101578040/225028146-01b0c3a4-422e-4073-995c-91e4429c759a.png)
![image](https://user-images.githubusercontent.com/101578040/225028246-351ba243-1e05-42a2-b16d-627155663b0c.png)

**Comment by jonmbake** [comment]
@MohammadSabriExalt Thanks for opening this issue. I'll work on fixing it within the next few days.

**Comment by jonmbake** [comment]
Fixed the bug. Opened a feature request, https://github.com/jonmbake/react-terminal-ui/issues/36, to add support for moving cursor with left/right arrows.

**Comment by MohammadSabriExalt** [comment]
@jonmbake , I appreciate the time and effort you put into this
